version: '3'
services:
  container1:
    image: frontend-image
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - container2
    environment:
      - REACT_APP_BASE_URL=https://container2:5003
  container2:
    image: backend-image
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGO_URL: "mongodb://your_username:your_password@mongodb:27017/?authMechanism=DEFAULT"
      - jwt_secret: secret
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: your_password
networks:
  mynetwork:
