apiVersion: v1
kind: Secret
metadata:
  name: mern-backend-secret
  namespace: mern-app
type: Opaque
data:
  PORT: NTAwMA==
  MONGO: bW9uZ29kYitzcnY6Ly9jaGlyYWc6Y2hpcmFnQGNsdXN0ZXIwLnh4cTd3dWcubW9uZ29kYi5uZXQvZG9jdG9yX2FwcD9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  JWT: a1cd158e2b34d47af6d0b446f59a326849f0dd8eb7ac51244f4ab4c1cb99552b9f856a8fb488f20fdbf0d489fc93b4d94fb71148a1bd24e2386a6c71e4d8a3cd